### ISSUE TITLE
Creator V2: Implement theme for a survey on the design surface

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#1203]

**Comment by dmitrykurmanov** [comment]
For now in master branch we have a problem with page's widht if we set the empty json:

```js
json = {}
```

**Comment by dk981234** [comment]
Need design:
Questions with startWithNewLine: false,
![image](https://user-images.githubusercontent.com/21283706/120992288-216b6500-c78b-11eb-9f59-fa6afca20e1f.png)
Matrixdynamic question:
![image](https://user-images.githubusercontent.com/21283706/120992576-698a8780-c78b-11eb-8f8d-b2a6c43ce379.png)
Boolean question (3 states instead of 2)
Rating question (hover, selected, disabled) states
Also, need a design for rating question when items do not fit container
![image](https://user-images.githubusercontent.com/21283706/120992802-9f2f7080-c78b-11eb-8949-42b357a716fc.png)
