### ISSUE TITLE
Not able to move question from one page to another on editing question in Modal Window

### ISSUE THREAD

**Issue by alexandrucostan** [surveyjs/survey-creator#1422]
### Are you requesting a feature, reporting a bug or ask a question?

Bug 

### What is the current behavior?

No able to move questions from one page to another. In the console i receive this error 

base.ts:1543 Uncaught TypeError: t.addElement is not a function
    at t.setPage (base.ts:1543)
    at t.set (question.ts:198)
    at t.e.updatePropertyValue (propertyEditorBase.ts:435)
    at e.onEditorValueChanged (objectProperty.ts:137)
    at t.editor.onChanged (objectProperty.ts:37)
    at t.e.onkoValueChanged (propertyEditorBase.ts:473)
    at f.ic.lc (propertyEditorBase.ts:83)
    at Function.notifySubscribers (knockout-latest.js:38)
    at Function.xa (knockout-latest.js:43)
    at t (knockout-latest.js:42)

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by andrewtelnov** [comment]
@alexandrucostan I have just tried and I could not reproduce it on [our website](https://surveyjs.io/create-survey). What version do you use? Could you please provide us steps to reproduce the issue?

Thank you,
Andrew

**Comment by alexandrucostan** [comment]
Hello, 
I am using version 1.8.41 with react. I have tried also to update to version 1.8.53 but i am receiving the same error. I am using survey-creator integrated with react. All the features it is working fine but this one isn't. If you have any suggestions that i can try. 

Thank you a lot for your support

**Comment by alexandrucostan** [comment]
Hello, 

I have managed to reproduce the bug also in your example pages 
 

![image](https://user-images.githubusercontent.com/6123913/123332368-15342580-d549-11eb-99d6-4d2f4bd194dd.png)

Here it is steps to reproduce 
When edit using this button and try to move question from layout menu to page 2 you will receive the error mentioned. If you try to move the answer from property will work.  Also in my code i have this settings showElementEditorAsPropertyGrid: false because i do not want to user right property, i want to have edit answer with pop-up 

![SurveyJs-bug](https://user-images.githubusercontent.com/6123913/123333196-19ad0e00-d54a-11eb-919f-e675aba875a2.png)

Thank you,

**Comment by andrewtelnov** [comment]
@alexandrucostan Ok, got it. It is not a default behavior. We have this modal window by default a long time ago and change it because a lot of UIX designers from different companies complained about it.
I hide "page" property from the modal window. We are editing a fake object in modal window and on "Apply"/"OK" button apply changes to the real object. There is no easy way to do it with the page, since we have to remove an element from the existing page and add it to a new page.
In the current property editor we are working with real objects and an user can rely on undo/redo functionality. So, we do not have this issue in the beginning.

Thank you,
Andrew

**Comment by alexandrucostan** [comment]
@andrewtelnov  Thank you for fix
