### ISSUE TITLE
Changing default value of showProgressBar creates progress bar inside property grid: V2

### ISSUE THREAD

**Issue by vikkrantxx7** [surveyjs/survey-creator#1481]
### Are you requesting a feature, report a bug, or ask a question?

Reporting a bug.

### What is the current behavior?

Changing defaultValue of showProgressBar creates a progress bar inside the property grid.

### What is the expected behavior?

The progress bar should not be created/visible inside the property grid.

### How would you reproduce the current behavior (if this is a bug)?

Providing the plunker example.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://plnkr.co/edit/aDNg7rsPsWBKTQzo

Test code

```
Survey.Serializer.findProperty('survey', 'showProgressBar').defaultValue = 'top'

```

### Specify your

* browser: chrome 91
* editor version: 1.8.55-alpha.1

![image](https://user-images.githubusercontent.com/37444378/125203799-b33d2500-e297-11eb-97ae-55c702015d34.png)

**Comment by andrewtelnov** [comment]
@vikkrantxx7 Yep, it is an interesting behavior. Property grid in fact is a Survey and it means that we should stop to rely on default properties values here, since developers can changed them. 
Thank you for letting know about the issue. We will think how to fix it, at the end, we will just set all these properties manually for property grid and other elements we are using in Creator.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@vikkrantxx7 Fixed by the commit above.

Thank you,
Andrew
