### ISSUE TITLE
Exception in react on adding a question into empty survey without pages, V2

### ISSUE THREAD

**Issue by AbhishekKS** [surveyjs/survey-creator#1518]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

In Creator V1, we don't allow deletion of all pages. So at least one page is always there in V1. The default Survey JSON in V1 is:
**{
 "pages": [
  {
   "name": "page1"
  }
 ]
}**
But in V2, we can delete even the ghost page which appears by default on the designer page. Is this an expected behavior in V2? 
If I delete the ghost page the Survey JSON becomes empty **{}**. And after I delete the ghost page, if I switch to some other tab and come back again on the designer page, and then add a question, I see a warning in the console. Not sure whether we are missing something here or what should be the desired behavior in V2.

![image](https://user-images.githubusercontent.com/13827554/125937639-9895bdfa-1da8-40d2-ab0a-ce6ea0f0ad15.png)

### How would you reproduce the current behavior (if this is a bug)?
1) Open the designer page first time with only the ghost page with no questions.
2) Delete the ghost page. Survey JSON becomes empty {}.
3) Click on some other tab and come back again to the designer tab and add a question.
4) I see a warning in the console.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

Test code

```
your_code_here

```

### Specify your

* browser: Chrome 91
* editor version:

**Comment by andrewtelnov** [comment]
@AbhishekKS We create one page on empty Creator. On deleting this empty page the ghost page is shown. We do not show a ghost page if the last page has not any question.
I am not able to reproduce the issue you see. Could you please provide a reproducible steps?
I can see a bug that we have to fix, "Page 1" is still selected in the Creator.

Regarding deleting the only page. We allow to delete it now because we have a ghost page.
An user may want to try Creator out. Drop several questions and then wants to start with blank survey/page. In this case allowing to delete the page with dummy question is a good solution.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@AbhishekKS There is no need in steps. I was able to reproduce the issue.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@AbhishekKS Indeed there is a memory leak. React tab components were not disposed properly since there were a link on them from our model objects. I have fixed it. 
The project should go away in several hours after somebody from the team approve my PR.

Thank you,
Andrew
