### ISSUE TITLE
Custom action item not visible creator V2.

### ISSUE THREAD

**Issue by vikkrantxx7** [surveyjs/survey-creator#1526]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug.

### What is the current behavior?

Custom action item created was working fine in 1.8.55 but in 1.8.56 it is not visible. Although it is visible in the popover for small screens.

### What is the expected behavior?

The icon should be visible.

### How would you reproduce the current behavior (if this is a bug)?

Providing the plunker example.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  https://plnkr.co/edit/iPyEbmEj61cnaTnd

Test code

```
const newItem = new Survey.ActionBarItem({
    id: "customToolbarButton",
    visible: true,
    title: "View Test",
    enabled: true,
    iconName: 'icon-delete',
    action: function () {
    }
})

creator.toolbarItems.push(newItem)

```

### Specify your

* browser: chrome 91
* editor version: 1.8.56-alpha.1

![image](https://user-images.githubusercontent.com/37444378/126046256-e83e3349-82f5-4665-ac47-5e8f3b42f2af.png)

![image](https://user-images.githubusercontent.com/37444378/126046265-d8cbfd42-2330-495c-9272-6b05991639cd.png)

**Comment by andrewtelnov** [comment]
@vikkrantxx7 We made a large refactoring in our toolbars classes. ActionBarItem doesn't work well in react or in knockout/vue like platforms. react can re-render the larger elements instead of re-rendering just one action, it could rerender the whole widget, or knockout/vue can get no notification about changes and do not update UI. As result we re-think it and re-work them during previos two weeks.
Anyway, please use the following code:

```js
const newItem = new Survey.Action({
    id: "customToolbarButton",
    visible: true,
    title: "View Test",
    enabled: true,
    iconName: 'icon-delete',
    action: function () {
    }
})
creator.toolbarItems.push(newItem)
```
To update UI you will have to change the properties directly, for example, `newItem.enabled = false;`. You could not use as before
`enabled: () => { return this.myReactiveBooleanProperty; }`

Thank you,
Andrew

**Comment by vikkrantxx7** [comment]
Thanks @andrewtelnov
