### ISSUE TITLE
hasComment not working as expected in V2

### ISSUE THREAD

**Issue by vikkrantxx7** [surveyjs/survey-creator#1606]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug.

### What is the current behavior?

has comment is not working correctly when it is checked then unchecked and then the tab is changed.

### What is the expected behavior?

has comment should render the editor on toggle.

### How would you reproduce the current behavior (if this is a bug)?

Providing the video.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  NA

Test code

```
No Code is required. Just make a question collapsible.

```

### Specify your

* browser: chrome 92
* editor version: 1.8.59-alpha.1

https://user-images.githubusercontent.com/37444378/128610459-6ceb85ab-df1c-4ad8-acb7-2adb81d79f37.mp4

**Comment by tsv2013** [comment]
Could you clarify - what's wrong with it?

**Comment by vikkrantxx7** [comment]
As you can see toggling hasComment is not rendering the editor below it

**Comment by AbhishekKS** [comment]
Hi,
This appears to be an issue rather than a question currently marked. The '**Has comment**' property does not work correctly. 
1) The input below Has Comment property does not appear on toggling after switching tabs.

![image](https://user-images.githubusercontent.com/13827554/128830834-ce55b38e-5744-4a4a-9bac-0c3c97d39597.png)

2) The comment text entered in the input does not reflect on the question in designer unless the tab is switched.
![image](https://user-images.githubusercontent.com/13827554/128830662-8c491858-f94c-46ac-8b91-2c3ac65c1a55.png)

Thanks
Abhishek

**Comment by tsv2013** [comment]
@AbhishekKS Don't worry. All tasks are in our task list and updated as soon as being processed.

**Comment by tsv2013** [comment]
>The input below Has Comment property does not appear on toggling after switching tabs.
I've not managed to reproduce it with the latest sources

>The comment text entered in the input does not reflect on the question in designer unless the tab is switched.
Reproduced, will work on the fix

**Comment by AbhishekKS** [comment]
Point 1 where the comment input text box disappears can be reproduced on your dev website. Steps to reproduce:
1) Open the designer page first time and add a radio question on the first page.
2) Switch Has comment to ON (checked) -> input textbox appears below. Switch Has comment to OFF (unchecked) again -> input textbox disappears. This seems fine until here.
3) Switch to some other tab, say Test Survey, and then come back on Designer Tab.
4) Now again Switch Has comment to ON (checked) -> **input textbox does not appear below.**

**Comment by tsv2013** [comment]
@AbhishekKS Thank you for the clarification, I see the issue now
