### ISSUE TITLE
V2: Logic tab, show Fast Entry in edit mode only

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/survey-creator#1933]
Show "Fast Entry" action when a user edit/create new logic item and hide it otherwise.

**Comment by AbhishekKS** [comment]
Hi,
I noticed 1-2 issues now in the current dev version on the logic tab on your test website, which seems small ones, thought of bringing this upfront so that we don't have to raise them after we upgrade to the 1.8.71 version (when it releases) in our environment. Can we fix them along with this ticket, or should I raise a separate ticket, please do let me know. 

1) On the Logic tab, as soon as I select a question in IF condition, the done button visibility is broken.
![image](https://user-images.githubusercontent.com/13827554/135710072-eb466273-70ea-448e-96b1-4ad67c8baa28.png)

2) Once I create logic on the logic tab, and when I reopen the logic without changing tabs, the question is not coming as selected in the IF condition.
![image](https://user-images.githubusercontent.com/13827554/135710174-6c10eccd-b1b5-4250-acff-b6bbb84972da.png)

Thanks
Abhishek

**Comment by OlgaLarina** [comment]
@AbhishekKS, this issue has already been fixed, I am creating separate issues for your described issues.
https://github.com/surveyjs/survey-creator/issues/1945
https://github.com/surveyjs/survey-creator/issues/1946

Thank you,
Olga
