### ISSUE TITLE
TypeScript: Invalid type declarations

### ISSUE THREAD

**Issue by supermacro** [surveyjs/survey-creator#2401]
### Are you requesting a feature, reporting a bug or ask a question?

We're trying to incorporate the surveyjs survey creator into our project (we, Caribou Inc, paid a license .. not sure if that warrants escalated support or not) however the project doesn't compile.  

### What is the current behavior?

Video: https://share.vidyard.com/watch/ASJXxiZbPVfUaVEibBZJfp

Repro: https://github.com/supermacro/survey-js-react-issue-repro

As you can see in the video, there are illegal assignments, name conflicts, invalid module structure (using UMD) and missing modules. 

### What is the expected behavior?

There shouldn't be any compiler errors. 

### How would you reproduce the current behavior (if this is a bug)?

https://github.com/supermacro/survey-js-react-issue-repro

**Comment by andrewtelnov** [comment]
@supermacro We did not try to create type react app with V2 so far.
I have created an [example in CodeSandbox](https://codesandbox.io/s/lucid-tree-5djgp?file=/src/SurveyEditor.tsx).
I beleive the CodeSandbox ignores typescript errors in the library. You can turn them off temporary and we will take a look on them. We will discuss it tomorrow.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@supermacro 
JFYI: We decided to move this issue up and include it into our current sprint. It is probably not so important issue for react, but important for Angular developers since typescript is the only choice for them.

We are using [dts-bundle](https://www.npmjs.com/package/dts-bundle) package. It has not been updated since 2017, however it is still the most used and suggested. The repository is dead on GitHub. We saw an open PR that fixed one of issues and there are many other issues found by us. We used to fix problems with d.ts generation by using regex expressions. As you can imagine, it is not a reliable approach.

We tried to find an alternative. Unfortunately, there is no any library that would satisfy us and be able to do what we need for Creator V2.  I would not say there are many of them. Google gives you examples for dts-bundle library mostly. 

As result, we decided to modify our [doc generation library] (https://github.com/surveyjs/surveyjs-doc-generator) to add code for bundle d.ts generation. I am working on it and hope to finish with it on the next week. We will try to add a compiler test into our CI for Angular, react and vue proejcts. They will test our d.ts files.

Thank you,
Andrew

**Comment by supermacro** [comment]
> Unfortunately, there is no any library that would satisfy us and be able to do what we need for Creator V2.

Can you elaborate on this? Maybe I can help find something. 

You might also want to look into [tsdx](https://github.com/jaredpalmer/tsdx), although I am not sure if it will meet all of your needs.

**Comment by supermacro** [comment]
Just came across this repo as well:

https://github.com/egoist/tsup

**Comment by andrewtelnov** [comment]
@supermacro We have create our own dts bundle generator and use it into Library and Creator.
We will use it in Pdf export and Analytics as well.
d.ts files are good in v1.9.4 that we have just released.

Thank you,
Andrew
