### ISSUE TITLE
Add routing logic to questions (e.g. If answer is A, jump to page foo, if answer is B, jump to page bar)

### ISSUE THREAD

**Issue by digitalronin** [surveyjs/survey-creator#244]
### Are you requesting a feature, reporting a bug or ask a question?

Requesting a feature

### What is the current behavior?

Pages are shown sequentially, with the option to hide some pages using "visibleIf".
i.e. Surveys are lists of pages, and after completing page 1, the user normally sees page 2, and so on.

### What is the expected behavior?

I would like to be able to build surveys which are more like trees than lists, so that the user's path through the survey depends on their answers to earlier questions.

e.g. I could design a survey where the questions I ask are very different for people who are employed, unemployed, students or retired. 

So, if the question was, "What is your work status?", then I could define a 'next page' attribute for the choices, something like this;

* Employed (next page: start_employed_section)
* Unemployed (next page: start_unemployed_section)
* Student (next page: start_student_section)
* Retired (next page: start_retired_section)

**Comment by andrewtelnov** [comment]
@digitalronin yes, right now you have to put a visibleIf on every page, except the first one.
The tree page concepts will definately complecate the UI.
There are some alternative solutions, for example sub-surveys, or triggers, when you may go to specific page and make any page the last one.
Anyway, there is a usability issue and it will be nice to solve it. 

Thank you,
Andrew

**Comment by digitalronin** [comment]
Hi Andrew

I agree that this feature introduces complexity - I think it could be worth it, though. Enabling a tree structure is very powerful, and one of the few things I think is missing from SurveyJS that would really put it far ahead of other form-building tools.

SurveyMonkey are the only similar product I've found that implements this feature. They allow attaching "logic" to questions, like this;

<img width="786" alt="screen shot 2017-12-23 at 10 33 11" src="https://user-images.githubusercontent.com/2338/34318974-d044f890-e7cc-11e7-9fbc-9ac7e8ac2a4b.png">

<img width="978" alt="screen shot 2017-12-23 at 10 33 23" src="https://user-images.githubusercontent.com/2338/34318977-db3f76d0-e7cc-11e7-9f16-d4ff4df0d396.png">

Something like that could be an option to consider.

Kind regards

David

**Comment by andrewtelnov** [comment]
@digitalronin Yes, we were thinking about this functionality.
In early versions of SurveyJS, we did not have visibleIf property. We have a visibility trigger. In our logic, you would have dog, cat and parrot pages make invisible first (visible=false) and then on setting the value make the needed pages visible - you may make visible several pages and questions at once. The functionality is still there.
The skip logic would work as well.
We decided to go with visibleIf, since a lot of our users have requested to support complex expression. For example, you may have two questions: sex (male/female) and birthdate and based on answers you may show different pages or panels, so your visibleIf should be like:
`visibleIf: "{sex} = 'male' and age({birthdate}) >= 21"`
Something that you are not able to do in the most survey engines. 
Anyway, the skip functionality is definately makes sense as well. Something that we will definately discuss for the next versions.

Thank you,
Andrew

**Comment by rafamontoya** [comment]
Any updates about this "skip"/"flow" proposed functionality? 
Thx again!
Rafa

**Comment by andrewtelnov** [comment]
@digitalronin @rafamontoya We have skip to question trigger now. Plus we have "Survey Logic" tab now, that can be used to view/edit all survey logic.

Thank you,
Andrew
