### ISSUE TITLE
Need rename placeholder for question selector in logic

### ISSUE THREAD

**Issue by dk981234** [surveyjs/survey-creator#3338]
Rename "Choose..." to "Select question..."

**Comment by dk981234** [comment]
![image](https://user-images.githubusercontent.com/21283706/183046275-14742ca3-f74b-4181-b579-92a506c3b43d.png)

**Comment by andrewtelnov** [comment]
@dk981234 @novikov82 @RomanTsukanov  Technically, it is not questions only. We can show matrix colums and calculated values.
We have "Selected elements..." that we do not use right now. I can use it. However, I beleive "Choose..." is good enough. Since it is the only dropdown to select from the beginning, a user will open a dropdown in anyway.

Thank you,
Andrew

**Comment by RomanTsukanov** [comment]
Then let's change it to "Select..." as per [advice by Microsoft](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui).

**Comment by OlgaLarina** [comment]
https://github.com/surveyjs/survey-creator/commit/09093c2060ef0cefb1ce93b9ad46db9a3e7e0197#diff-443d025b0cc0e996a7703312805e840d06f2212104ff74eb1c418d9926ea56ff
