### ISSUE TITLE
The Choices from a RESTful service | Store answers in the following JSON field property name and description doesn't match the `ChoicesRestful | valueName` property name/description

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#3677]
The `Choices from a RESTful service | Store answers in the following JSON field` property corresponds to the `ChoicesRestful | valueName` property and specifies which field contains choice values. However, the Property Grid displays the irrelevant property name and the description. Open this demo in Creator, select the first question and navigate to the Property Grid | Choices from a RESTful service tab to reproduce the issue : [Dropdownrestful](https://surveyjs.io/form-library/examples/questiontype-dropdownrestfull/reactjs).

![image](https://user-images.githubusercontent.com/22372972/202179841-441f58c5-0455-4c14-898d-b2ad7cf9f641.png)

Expected behavior: the property has a relevant name and description.

**Comment by RomanTsukanov** [comment]
The caption should read:

"Get values from the following JSON field"

But please be careful: the current caption is also valid because it is properly used for an editor in the Data tab. We cannot simply replace the current caption with the new one.

![image](https://user-images.githubusercontent.com/18551316/202658188-3494f6fc-431e-4412-af91-b818f463056e.png)
