### ISSUE TITLE
Some translations still overlaps

### ISSUE THREAD

**Issue by rendaforstmane** [surveyjs/survey-creator#3783]
Hello, @andrewtelnov !

Thanks for the previous bug fix.

But I found new strings in several questions where there are still incorrect translations, even though the current locale is "en".

Example:
https://codesandbox.io/s/surveyjs-creator-vue-forked-gsvfvp?file=/src/components/SurveyCreatorComponent.vue

![Screenshot 2023-01-16 at 13 54 30](https://user-images.githubusercontent.com/84146240/212673250-f3beebbf-e7a8-43cb-b918-26b3fb2736dd.png)

_Originally posted by @andrewtelnov in https://github.com/surveyjs/survey-creator/issues/3761#issuecomment-1368960243_

**Comment by JaneSjs** [comment]
Hello @rendaforstmane,
You set the `lv` locale for the SurveyJS Form Library:
```
SurveyKO.surveyLocalization.defaultLocale = "lv";
```
Therefore, survey questions display [Latvian text](https://github.com/surveyjs/survey-library/blob/master/src/localization/latvian.ts#L12) for the `otherItemText` value. 

Please let me know your overall goal. What result do you expect by setting the `defaultLocale` to `lv`?

**Comment by rendaforstmane** [comment]
Please explain the difference in these translations for individual buttons.
1) currentLocale `en`, defaultLocale `lv`  popup action buttons in `en`, but some strings in questions `lv`
![Screenshot 2023-01-16 at 15 42 22](https://user-images.githubusercontent.com/84146240/212692453-030bfd1a-6f2c-4c49-9d9d-dfdb9f3f234e.png)
2) currentLocale `lv`, defaultLocale `en`  popup action buttons in `lv`, but some strings in questions `lv`
![Screenshot 2023-01-16 at 15 42 53](https://user-images.githubusercontent.com/84146240/212692460-dfd17de4-199c-4cc9-9d3e-7ac349f8e33a.png)

If currentLocale is `en` and defaultLocale is `lv`, I expect to see all strings in `en`.
If currentLocale is `lv` and defaultLocale is `en`, I expect to see all strings in `lv`, if `lv` string does not exist, I expect to see all strings in `en`. Do I understand correctly?

Thanks!

**Comment by JaneSjs** [comment]
Hello @rendaforstmane,
I believe the issue is that you're mixing up localization instances from different modules.
Please let me clarify things.

The `surveyLocalization` imported from `survey-core` sets the translation for survey contents: [Form Library: Localization](https://surveyjs.io/form-library/documentation/survey-localization).
So, the `defaultLocale` sets the locale which will be used as a fallback locale - when the `currentLocale` doesn't contain required texts. If you set the `defaultLocale` to `lv`, and `currentLocale` to `en`, Latvian texts will be used if English strings are missing for survey contents.
```
import { surveyLocalization } from "survey-core";

surveyLocalization.defaultLocale = "lv";
surveyLocalization.currentLocale = "en";
```

If you wish to translate Survey Creator UI, use the `localization` instance from `survey-creator-core`: [Localization & Globalization](https://surveyjs.io/survey-creator/documentation/localization).
```
import { localization } from "survey-creator-core";

localization.currentLocale = "en";
```
[Example](https://codesandbox.io/s/surveyjs-creator-vue-forked-kfho1t?file=/src/components/SurveyCreatorComponent.vue).

Please test the updated example. Let me know if any questions remain.
