### ISSUE TITLE
Introduce an adorner for image picker items editing

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#391]
ImagePicker improvement: upload image into service, including external service, and add addorner with ability to add/delete the image.
We are working on this functionality right now. Our service will allow to post images from the local computer and return the link on them that you will be able to use. You will be able to re-use your own service with our UI.

https://surveyjs.answerdesk.io/ticket/details/T969

**Comment by SamMousa** [comment]
@tsv2013 I think this has already been implemented via the `onUploadFile` event.

What I am missing is an image picker control, I would suggest a very simple integration that doesn't break BC.

- Leave `onUploadFile` the same
- Add property `mediaPicker` that takes a function.

When clicking the + to add an image in the image question type (and image picker and possibly other locations like survey logo), check if `mediaPicker` is set. If not, use the file selector combined with `onUploadFile` as you do now.
If `mediaPicker` is set, call the function with a signature like this:
```js
survey.mediaPicker(cancel, pick, mediaType);
// Signature of cancel
cancel();
// Signature of pick
pick(mediaUrl);
```

This will allow 3rd party devs to easily integrate external file managers while keeping the code on your side very simple. Note that `onUploadFile` currently uses the event system; this feels kind of unnatural to me since the behavior of multiple event handlers is not really specified.
When using the event driven approach, it makes sense that all events can support multiple handlers. For things like `uploadFile` to meaningfully support multiple events there should be some kind of information exchange between event handlers.

Consider a scenario where I want to have an event handler that uploads large files to a web service, but for small files uses the data URI approach.
A clean way would be to attach 2 handlers, the first one that is called then sets something on the event, like `event.uploadHandled = true` signalling that other event handlers shouldn't attempt to upload the file.
Note I'm specifically not using something generic `event.handled` here, there might be another event handler attached that logs something to the console that should always run, regardless of whether a file was uploaded.

Regardless of which architecture you choose, this would be a great feature that feels simple to implement (to me).
If you let me know which you prefer (I'm guessing it'll be something like `onPickFile`) I am happy to make a PR for it.

**Comment by tsv2013** [comment]
What doesn't allow you to implement a `mediaPicker` as a wrapper over the `onUploadFile` event?

**Comment by SamMousa** [comment]
The `onUploadFile` is triggered after the user selects a file to upload in the browser, so that means that showing a picker at that point makes no sense. It wouldn't allow a flow where a user chooses an image that was uploaded previously.

**Comment by tsv2013** [comment]
We can pass an object, property name and an old value in the options of the event. Will it cover your scenario? I hope you understand our interest in the minimum of entities/events/approaches set here.

**Comment by SamMousa** [comment]
>  I hope you understand our interest in the minimum of entities/events/approaches set here.

I do. But overloading events with extra argument is really not a better choice.
Having small events that do very specific things makes your code simple. Having events that pass around a lot of data for a lot of different use cases makes your code complex...

But maybe I'm misunderstanding something here. The `onUploadFile` event is triggered AFTER the user has selected a file; so it will never be to properly handle the case I'm presenting.
I want to be warned before the file upload box is shown and show my own UI instead; this UI could then allow people to pick images from the server.

**Comment by tsv2013** [comment]
We can introduce an event to show custom file chooser. Will it be ok for you?

**Comment by SamMousa** [comment]
Yeah definitely

**Comment by tsv2013** [comment]
I've added the following event to survey creator:
```JS
  /**
   * The event is fired then one need to choose files.
   * <br/> sender the survey creator object that fires the event
   * <br/> input file input HTML element
   * <br/> callback need to be called after files has been chosen
   * @see uploadFile
   */
  public onOpenFileChooser: Survey.Event<
    (sender: SurveyCreator, options: any) => any,
    any
  > = new Survey.Event<(sender: SurveyCreator, options: any) => any, any>();
```

You can use it the following way:
```JS
creator.onOpenFileChooser.add(function(sender, options) {
    var chosenFiles = myFIleChooser.choose();
    options.callback(chosenFiles);
});
```
