### ISSUE TITLE
Arranging questions in columns within a panel

### ISSUE THREAD

**Issue by naoey** [surveyjs/survey-creator#421]
### Question

We have a need for a panel with a "columns" property which essentially creates a panel with child panels in a column arrangement within which we can drop questions. I tried experimenting with the default panels and width property but it wasn't very intuitive for this use case. Can I get some advice as to how I can create another "panel" item in the toolbox on which we can simply specify the number of columns it should contain to get the desired layout?

The functionality we are looking for is slightly similar to the matrix items but for the columns to be panels in which we can drop other questions.

I also noticed setting the "width" property on an item doesn't resize it in the editor until another item is added/removed. I believe this is a bug?

**Comment by tsv2013** [comment]
There are one question and one bug.

How to create a panel with columns? Yes it's possible: you need to create a custom widget based upon the panel. Once it will be created, it can be used in the SurveyJS Bulder. We have a documented sample - how to create a custom widget (https://plnkr.co/edit/fXsLf1R88WxxDFaFEnYx?p=preview). But it can be rather complex to imeplement due to it should support drag/drop items to/from the columns. And this looks like an enchancement for me. We'll discuss this feature with the team. @andrewtelnov @dmitrykurmanov 

The changes of the "width" property are not reflected in UI immediately. Yes it's a minor bug and it will be fixed. Please track the https://github.com/surveyjs/editor/issues/422 issue.

**Comment by naoey** [comment]
Closing this as a stale issue. We are more familiar with the editor now and were able to achieve what we wanted through the use of panels with predefined widths.

**Comment by pashaie** [comment]
@naoey Can you explain your approach in more details? we have similar requirements and looking for possible workarounds. thanks

**Comment by andrewtelnov** [comment]
@Palachun Drop two panels and set to the second panel the property "startWithNewLine" to false.

Thank you,
Andrew

**Comment by pashaie** [comment]
@andrewtelnov  thanks, got it!
