### ISSUE TITLE
Automatic Escaping of Line Breaks

### ISSUE THREAD

**Issue by AkaHanshan** [surveyjs/survey-creator#4399]
In surveyjs, when adding line breaks to properties like "description" using the property grid, clicking on the "description" field in the designer will cause the line breaks that were originally present in the JSON to be escaped as empty characters.

here is the example code: https://codesandbox.io/s/sharp-ganguly-2dzgj9?file=/src/survey_json.js
the screen shoot 

https://github.com/surveyjs/survey-creator/assets/48984202/fbce2bf8-1292-42c8-a0cd-195b3a453121

**Comment by JaneSjs** [comment]
Hi @AkaHanshan,
Line breaks are automatically escaped because a survey doesn't accept a carriage return in question titles and descriptions.

If you wish to display a multi-line text in a question's title/description, please register a [Markdown text processing library](https://surveyjs.io/form-library/examples/edit-survey-questions-markdown/reactjs) and format the text as your needs dictate.

To edit Markdown text for survey elements, you can also register a custom rich text editor. For instance, as it's demonstrated in our online demo: [Custom Property Editor](https://surveyjs.io/survey-creator/examples/add-custom-property-editor/reactjs).

I hope this information helps. Should you have any questions or require further assistance, we are here to help.
