### ISSUE TITLE
Setting different default language breaks translation

### ISSUE THREAD

**Issue by dennisfischer** [surveyjs/survey-creator#460]
### Are you requesting a feature, reporting a bug or ask a question?
This is a bug report.

### What is the current behavior?
I'm trying to set a different default language (de). The builder outputs following JSON:
```json
{
 "locale": "de",
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "radiogroup",
     "name": "question2",
     "choices": [
      {
       "value": "0",
       "text": {
        "default": "Nein",
        "en": "No"
       }
      },
      {
       "value": "1",
       "text": {
        "default": "Vielleicht",
        "en": "Maybe"
       }
      }
     ]
    }
   ]
  }
 ]
}
```

Changing to english (en) isn't working. The builder test survey continues to show the german default.

### What is the expected behavior?
After changing the language I'd expect to see the english translations.

### How would you reproduce the current behavior (if this is a bug)?
Use the JSON from above.

### Specify your

* browser: Chromium 71
* editor version: 1.0.65

**Comment by andrewtelnov** [comment]
@dennisfischer Your default locale is "de" and not "en". It means that you have created the survey JSON with German default locale: `Survey.surveyLocalization.defaultLocale = "de";`
You have to set this code on your page as well. Here is [the example](https://plnkr.co/edit/TMcly3DtzKLoa1yRIJlK?p=preview) or change your json: "default" to "de" and "en" to "default".

Thank you,
Andrew

**Comment by dennisfischer** [comment]
@andrewtelnov This means we can only set the defaultLocale as a global setting? Also, from that I assume having two surveys on a page with different default locales is not possible?

Thank you,
Dennis

**Comment by dmitrykurmanov** [comment]
@dennisfischer Does two surveys with different default locales at the same time in one page is really need?  Could you please describe your use case in greater details? It might be a new feature of the library or we could try to suggest something. Thanks.

**Comment by dennisfischer** [comment]
Well, not sure if this is a need. Just asking if I see that correctly. At very least this is a code smell imo.

**Comment by andrewtelnov** [comment]
@dennisfischer The idea is simple, by setting `Survey.surveyLocalization.defaultLocale = "de";` you are chaging the default language from "en" to "de" and all "default" strings becomes "de" strings and not "en" strings.
If you do not want to have two (or more) languages in your survey, and the most surveys have only one language, a localizable string would look like: myProperty: "My String Value", insteard of myProperty : {default: "My String Value"}. Some people construct survey json in text editor and it would be overcomplecated for them to learn about multi-language support since they just do not need it.
I hope it becomes clear a little bit.

Thank you,
Andrew
