### ISSUE TITLE
A theme specified using the `theme` property is not applied to a survey unless the Themes tab is activated

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#4686]
User Issue: T14884 - Customize Designer Font
https://surveyjs.answerdesk.io/internal/ticket/details/T14884
***
A theme assigned to `creator.theme` is not applied unless a developer enables `showThemeTab`. 
Suggestion: apply a custom theme regardless of the Theme Tab visibility.

**Comment by tsv2013** [comment]
@vitality82 Here is the working example with the latest version 1.9.112 - https://plnkr.co/edit/qJpZLPu4e1DiXuVB
It works ok for me - custom theme is applied in preview (test) ant theme tabs.
As for designer tab - it is not supposed to apply theme in designer tab - theme customizations can break inplace editing on design surface.
In survey runtime (when one takes a survey) you need to call the `applyTheme` method with a theme object JSON. It described in this documentation article - https://surveyjs.io/form-library/documentation/manage-default-themes-and-styles.

If you still have some issues with apply theme functionality, please share a minimal working example illustrating the problem in another thread on GitHub.

**Comment by vitality82** [comment]
@tsv2013 the bug is still there but under different circumstances from your basic setup. Here:

1. We are not rendering the tabs (Designer, Previewer, etc) because we have our own sub navigation/tabs on our page, changing the mode is done programatically ( creator.showPreview() )
2. 
<img width="1362" alt="image" src="https://github.com/surveyjs/survey-creator/assets/3256598/fbf3e08f-cb2a-4fe7-a9dc-e3bab753101f">

When showDesigner = false, the theme is not loaded, unless the order is:

`creator.theme = themeJSON;
    creator.JSON = formJSON;`

instead of 
`creator.JSON = formJSON;
    creator.theme = themeJSON;`

Sounds like I'm opening up a can-o-worms by using "showDesigner: false" and I'd probably be better of hiding the tabs with css?
