### ISSUE TITLE
onOpenFileChooser event is not fired from property grid

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#4687]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
The file chooser event is not fired from the property grid, for example for Survey Logo or Image Picker choices
![image](https://github.com/surveyjs/survey-creator/assets/547021/00d84343-6959-4002-8161-020c1104fe08)

### What is the expected behavior?
It should fire for all file inputs from the property grid, the same as it does for editor decorators (not sure if thats the right term):
![image](https://github.com/surveyjs/survey-creator/assets/547021/4484c6d0-625b-48b8-86d5-91fd4fd16fa4)

### How would you reproduce the current behavior (if this is a bug)?

1. Navigate here: https://codepen.io/sammousa/pen/mdazope
2. Click the icon next to **Survey Title**, confirm you get a javascript alert.
3. Go into the property grid, **Logo in Survey Title**
4. Click the icon next to the logo input
5. See that the javascript alert is not triggered.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codepen.io/sammousa/pen/mdazope

**Comment by JaneSjs** [comment]
Hello @SamMousa,
Thank you for reporting this issue. I confirmed that the [creator.onOpenFileChooser](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#onOpenFileChooser) event is not fired when a user clicks the file upload button via a property grid. I'll forward this issue to our developers.
Meanwhile, please let me clarify your usage scenario. Do you use this event to override the standard file chooser?

**Comment by SamMousa** [comment]
Yes I do. We use a file picker / media manager to allow the user to pick already uploaded files as well as upload new ones.

**Comment by JaneSjs** [comment]
Hello @SamMousa,
Thank you for the update. I forwarded this issue to our developers for further research.

Regarding your additional question: without a callback function, files won't be processed or handled in any way, and the [creator.onUploadFile](https://surveyjs.io/survey-creator/documentation/api-reference/survey-creator#onUploadFile) function won't be executed. However, if a user cancells the file upload action, you can return from a function by calling the `return;`, like it's done in our source code: https://github.com/surveyjs/survey-creator/blob/63c3a46384d53ee8044763adec7ab551313a3577/packages/survey-creator-core/src/creator-base.ts#L2777C63-L2777C69. As you can see, if no files are selected (e.g., if the user cancels the file dialog), the code simply returns and does nothing further. In this specific case, not providing a callback function won't cause any unhandled results or actions because the code handles the scenario where no files are chosen. You can implement a similr routine to handle file uploads in your code.

Please le tme know if you have any further questions.

**Comment by SamMousa** [comment]
Hi @JaneSjs, I think I haven't explained my additional question correctly.
Even though from your answer I can extract what I need to know...

I was talking about the fact that the documentation (see my image above) says:

> `options.callback` - need to be called after files have been chosen

The docs don't tell us about what to do if the user canceled the action. From your answer I conclude that I simply do not call the callback.

You also mention to just "return from the function", but this suggests a lack of understanding of asynchronous programming. My function always instantly returns... I launch the popup for the file picker, and give it the callback. Then I return from the function without waiting for the dialog to appear, or the user taking any action.

Anyway, thanks for your time, I look forward to the bugfix!
