### ISSUE TITLE
Changing the names of elements of multipletext questions removes previously set default values

### ISSUE THREAD

**Issue by chamgda** [surveyjs/survey-creator#4811]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
Changing the names of elements of multipletext questions removes previously set default values

### What is the expected behavior?
Changing the names of elements of multipletext questions keeps previously set default values

### How would you reproduce the current behavior (if this is a bug)?
1. Add a question of type multipletext to the survey
2. Set default values for the elements of the question
3. Change the names of the elements of the question
-> the keys of the elements in the defaultValue object of the question in the resulting JSON are not updated to the new names, effectively removing the default values; the default values are still visible in the editor but not in the preview

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://surveyjs.io/survey-creator/examples/free-nps-survey-template/reactjs

Test code

```
your_code_here

```

### Specify your

* browser: Chrome 118.0.5993.89
* editor version: whatever version your demo page is on

**Comment by JaneSjs** [comment]
Hello @chamgda,
Thank you for reporting this issue. I'll discuss it with the team and update you shortly.

An example of a Multiple Textboxes question after upding item names:
```
{
 "pages": [
  {
   "name": "page1",
   "elements": [  
    {
     "type": "multipletext",
     "name": "question2",
     "defaultValue": {
      "text1": "test value 1",
      "text2": "test value 2"
     },
     "items": [
      {
       "name": "text11",
       "title": "text1"
      },
      {
       "name": "text22",
       "title": "text2"
      }
     ]
    }
   ]
  }
 ]
}
```

**Comment by JaneSjs** [comment]
Hello @chamgda,
I discussed this issue with our developers. It appears that the default value is not actually updated when Multiple Textboxes' item values are changed. Neither we update default values for matrices, when their column/row names are updated.

Unfortunately, we may not address this issue at this time, because this would require significant updates for various SurveyJS built-in question types.

We appreciate your understanding. In the meantime, we recommend that you manually update a question's default value once you modify the item values.

Thank you
