### ISSUE TITLE
I have several questions with the survey creator.

### ISSUE THREAD

**Issue by chaklasiyanikunj** [surveyjs/survey-creator#5221]
1. How do you use the date picker component with the survey creator? I checked it's available on your website with a third party, but is there any way to use it with the survey creator?

2. I used the matrix below to create table-wise content. Is there any way to assign different data types to columns using a matrix?
![Matrix](https://github.com/surveyjs/survey-library/assets/39697799/4746b889-8d61-45f8-910f-9baf31f204d8)

3. Can we merge the column name like the below image using a matrix?
![MergeColume](https://github.com/surveyjs/survey-library/assets/39697799/ac438561-b1c1-4c42-828d-93430c994bcf)

4. Can we assign the HTML type to the Column in Matrix?

5. Can we write only text inside Column  in the matrix?

**Comment by JaneSjs** [comment]
Hello @chaklasiyanikunj,
1. You can register a third-party widget within the SurveyJS Creator. For more information, please refer to the following demo: [Integration with Third-Party Libraries](https://surveyjs.io/survey-creator/examples/integration-with-third-party-libraries/reactjs). If you are developing a [React](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-react)/[Angular](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-angular)/[Vue 3](https://surveyjs.io/form-library/documentation/customize-question-types/third-party-component-integration-vue) app, please consider implementing a corresponding UI component and integrating it within the SurveyJS Form Library and Creator.

2. If you wish to configur different column types for a table-like input element, consider using a [Multi-Select Matrix question](https://surveyjs.io/form-library/examples/multi-select-matrix-question/).

3. Unfortunately, merging column names is not possible with a SurveyJS Matrix.

4. Yes, you can set the `cellType` to `html`. However, as HTML is a read-only field type and it doesn't allow user input, you won't be able to define different content within cells. Perhaps, the [Expression](https://surveyjs.io/form-library/examples/expression-question-for-dynamic-form-calculations/reactjs) cell type will work for you. Please clarify your end goal so that I can consider an option.

5. To enter text within matrix columns, set the `cellType` to `text` or `comment`.

I hope this information helps. Please let me know if you have additional questions.

Additionally, let me note that SurveyJS Creator is a commercial product and it requires a developer license. For more information, please visit [Licensing](https://surveyjs.io/licensing).

**Comment by chaklasiyanikunj** [comment]
Thank you so much for your Great Response.

I was satisfied with the first 3rd answer.

For the 4th and 5th points, Using matrix, I need to add a bullet point in the row like the below image.

![multi matrix](https://github.com/surveyjs/survey-creator/assets/39697799/e1e50ed9-6d5e-42d6-8d4f-03dcc5531dd8)

Additionally,

Is there any way to put all the radio button or checkbox in single row?
![SingleLineRadioButton](https://github.com/surveyjs/survey-creator/assets/39697799/b8168b84-42e7-4e2a-8de5-f37b2627a13e)

**Comment by chaklasiyanikunj** [comment]
Any update on this issue?

**Comment by chaklasiyanikunj** [comment]
Any update on this issue?
