### ISSUE TITLE
Add validation for visibleIf and enableIf on changing question name

### ISSUE THREAD

**Issue by benirose** [surveyjs/survey-creator#562]
### Are you requesting a feature, reporting a bug or ask a question?
Requesting a feature

### What is the current behavior?
There is no validation on visibleIf or enableIf. If I change a question name that is being used in a visibleIf expression, the question with a visibleIf will now never display because the question name is wrong in the expression.

### What is the expected behavior?
When I modify a question name being used in an expression in visibleIf or enableIf, it should update the values in those visibleIf and enableIf fields, or at minimum present errors saying those questions have invalid expressions.

**Comment by andrewtelnov** [comment]
@benirose Yep, it is in our TODO list. We are going to add: `creator.renameQuestion(question, newName)` function. It is going to use a new SurveyLogic class (branch: logic_tab). There are more then just these two. We have also: requriedIf, completed html on condition, expressions and survey triggers. 

Thank you,
Andrew

**Comment by benirose** [comment]
Awesome! Any anticipated timeline on this? I can stub in a check using `onModified` in the mean time but would obviously rather have it native. Thanks for the great work!

**Comment by andrewtelnov** [comment]
@benirose I am working on Logic tab right now. I really hope it will take about 2-3 weeks. We will  document and add examples with this tab at the beginning. We will ask people who request it to take a look. However, this functionality we may make available immediately, since there is no any UI here and all we need is to call one function.
SurveyLogic class finds all conditions/expressions, it will be reasonable to include this functionality into this class.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@benirose The functionality will be availalbe in the next minor update 1.1.6, likely on August, 20. We update all conditions/expressions in the survey: visibleIf, enableIf, requriedIf, choicesVisibleIf, choicesEnableIf, rowsVisibleIf, columnsVisibleIf, triggers expressions, validators expressions, expression of Expression Question, total expression for marix column and so on.

Thank you,
Andrew
