### ISSUE TITLE
"Invalid object that looks like an observable; possibly from another Knockout instance"

### ISSUE THREAD

**Issue by MinWook6457** [surveyjs/survey-creator#6003]
**Describe the bug**
Hi survey team.

Here is my survey creator code.
```
const surveyCtl = {
			_name: "surveyCreatorContainer",
			_creator: undefined,
			_creatorOptions: {
				useKnockout : false,
				showLogicTab: true,
				isAutoSave: true
			},
			_creatorTheme: {
				isPanelless: true
			},
			init: function(){
				Survey.setLicenseKey(
						"my licence key"
				);

				this.creator = new SurveyCreator.SurveyCreator(surveyCtl.creatorOptions);
				this.creator.themeForPreview = "plain"

				this.render();
			},
			render: function(){
				this.creator.text = $("#formJson").val() || '{"title": "Survey Title","logoPosition": "right","pages": [{"name": "page1"}]}';
				this.creator.render(this.name);
			},
			get name(){
				return this._name;
			},
			set name(value){
				this._name = value;
			},
			get creator(){
				return this._creator;
			},
			set creator(value){
				value.theme = this._creatorTheme;
				this._creator = value;
			},
			get creatorOptions(){
				return this._creatorOptions;
			},
			set creatorOptions(value){
				this._creatorOptions = value;
			}
		}
```

issue is 

```
"Invalid object that looks like an observable; possibly from another Knockout instance"
```

I am using the library by importing it from cdn, not npm, into an internal project.

![image](https://github.com/user-attachments/assets/6a05a146-1614-4614-ac7b-fa87c087ffd6)

![image](https://github.com/user-attachments/assets/d2d07deb-9756-4136-84ce-bb6efe9bc3b1)

I decided that the 'knock out' library version was not correct and gave the survey an option to ignore it, so it failed.

```
const surveyCtl = {
			_name: "surveyCreatorContainer",
			_creator: undefined,
			_creatorOptions: {
				useKnockout : false,
				showLogicTab: true,
				isAutoSave: true
			},
			_creatorTheme: {
				isPanelless: true
			},
                       ...
```

how to fix it..?

**Comment by JaneSjs** [comment]
Hi @MinWook6457,
You may probably know that with one of recent SurveyJS component updates, we introduced framework-agnostic, Knockout-free UI rendering bundles for vanilla JavaScript applications. For more information, please visit [SurveyJS v1.11.12 | Knockout-Free UI Rendering Bundles](https://surveyjs.io/stay-updated/release-notes/v1.11.12).
I would recommend that you consider using the `survey-creator-js` library instead of Knockout. Please follow [Add Survey Creator / Form Builder to a JavaScript Application](https://surveyjs.io/survey-creator/documentation/get-started-html-css-javascript) and update your application to new bundles. Let me know if it fixes the issue.
