### ISSUE TITLE
Invalid CSS breaks survey-core with NextJS 15

### ISSUE THREAD

**Issue by iotashan** [surveyjs/survey-creator#6040]
https://github.com/surveyjs/survey-creator/blob/f33bd2321dfff2a37bfee68ed93ab0791cf58be8/packages/survey-creator-core/src/components/simulator.scss#L70

`::i-block-chrome` is not valid CSS, and breaks if you try to use survey-creator-react with Next.js 15

`import 'survey-creator-core/survey-creator-core.min.css';`

> Unsupported pseudo class or element: i-block-chrome

**Comment by tsv2013** [comment]
This was done to fix the https://github.com/surveyjs/survey-library/issues/5507 issue
And reserve place for scroll bar in safari - https://github.com/surveyjs/survey-creator/commit/e28ef3cf2a17c63e79d0d01c834d9123a11e7591

**Comment by tsv2013** [comment]
@iotashan Probably you can setup skip this rule check for this code, or for the whole `survey-creator-core.min.css` file

**Comment by JaneSjs** [comment]
Hello @iotashan,
I created a fresh NextJS 15 application (v15.0.3). Please download it at 
[next-15.zip](https://github.com/user-attachments/files/17678026/next-15.zip). I successfully ran the `npm run dev` and `npm run build` commands and didn't get the mentioned error. 
Please try the demo on your end and clarify how to reproduce the issue.

Thanks

**Comment by ojkaas** [comment]
I also get the same error, tried the demo project and that works, set the package version to the same versions in my project, but then I get the same error.  Will try to see if I can create something reproducible but the current project I cannot easily share. Any tips in the meantime how I could skip this check?

**Comment by JaneSjs** [comment]
Hello Everyone,
@ojkaas, thank you for contacting us. I would appreciate it if you could recreate this issue on a sample demo and share it for research. In the meantime, you can try to suppress this warning using the following options.

In Next.js, you can configure PostCSS to ignore non-standard CSS rules. Add or modify your postcss.config.js as follows:
```
module.exports = {
  plugins: {
    'postcss-custom-properties': {}, // Include other plugins as needed
    'postcss-preset-env': {
      stage: 0,
      features: {
        'custom-selectors': false, // Disable optimizations for non-standard selectors
      },
    },
  },
};
```
Alternatively, modify your Webpack configuration in next.config.js to suppress CSS warnings related to `::i-block-chrome`.
```
module.exports = {
  webpack: (config) => {
    config.module.rules.push({
      test: /\.css$/,
      use: [
        {
          loader: 'css-loader',
          options: {
            warn: false, // Suppress CSS warnings
          },
        },
      ],
    });
    return config;
  },
};
```
I hope that either option can help you.

**Comment by naganikhilbijjala** [comment]
Hi @JaneSjs, 
I am also facing the same issue. It occurs when I enable Turbopack instead of using Webpack.

To reproduce the issue, you can modify the package.json file to enable Turbopack for next dev like this:

  `"scripts": {
    "dev": "next dev --turbopack",
}`

In Next.js 15, Turbopack is enabled by default for the development server when using create-next-app. I think it doesn't support certain CSS syntax, which is causing the error. https://nextjs.org/docs/app/api-reference/turbopack#unsupported-features

When I remove this line in the css file `::i-block-chrome,` everything works fine.

I have recreated the issue, and  you can check it in this codesandbox link https://codesandbox.io/p/devbox/v8r5hm


![image](https://github.com/user-attachments/assets/df2f7256-e6fa-428b-a22a-1433168c7496)
