### ISSUE TITLE
Read Only Feature not working

### ISSUE THREAD

**Issue by bhp2810** [surveyjs/survey-creator#608]
### What is the current behavior?
I have set Form Design and saved data in database. I have used Dropdown Element.
I set dropdown field as readonly and saved it. 

When I come back after save as readonly, Option is showing readonly but when i go to advance tab option in right side of form builder it not shows  "Read Only" as selected. and when I click on read only select/unselect effect not showing on element.

### What is the expected behavior?

Allow to select/unselect and make effect on element as per check/uncheck.

### How would you reproduce the current behavior (if this is a bug)?

May be implemented demo on server by user wise login functionality.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

![Screenshot_1](https://user-images.githubusercontent.com/46674257/66107034-ef305a00-e5dc-11e9-93cf-2d559a7df230.png)
![Screenshot_2](https://user-images.githubusercontent.com/46674257/66107036-ef305a00-e5dc-11e9-99f1-8c2f99e9bceb.png)

**Comment by andrewtelnov** [comment]
@bhp2810 All questions are read-only in designer surface. Please go to "Test Survey" tab and see the difference.

Thank you,
Andrew

**Comment by bhp2810** [comment]
hello,

It stay same as in designer surface. not any effect. please advise. how can I manage read only option. 

If i save in one pc and check in other it not worked and not allow to remove  readonly option.

Thanks

**Comment by bhp2810** [comment]
I show data by using below method after save in database.

var survey = new Survey.Model(json);
        $("#build-wrap-surveyjs").Survey({
            model:survey
        });

**Comment by tsv2013** [comment]
As Andrew wrote before, the "Read Only" property of a question tells whether this question will be read only in run time - when this survey/form will be running.

Here I set the "Read Only" ptoperty for the first question:
![image](https://user-images.githubusercontent.com/3013415/66393487-53875b00-e9db-11e9-8f25-6b5742e07f9a.png)
The "Test survey" tab shows how the survey will behave in runtime. As you can see, quetion1 is read-only while question2 is not:
![image](https://user-images.githubusercontent.com/3013415/66393559-8af60780-e9db-11e9-8bc3-dacb9cde3258.png)

The same behavior will be in runtime. And this is the expected behaviour.

If you've got somthins else, please provide us with a live minimal sample illustrating the issue or steps to reproduce it in our demos.
