### ISSUE TITLE
Unable to Drag drop when same names set for question 

### ISSUE THREAD

**Issue by VishalWaman** [surveyjs/survey-creator#628]
### Are you requesting a feature, reporting a bug or ask a question?
Ask a question

### What is the current behavior?
Unable to Drag drop when same names set for question 

### What is the expected behavior?
Even if we set same name to question "options.question.name" it should be dragabble  

#### Provide the test code and the tested page URL (if applicable)

    this.surveyCreator.onQuestionAdded.add(function(sender, options) {
      var q = options.question
      var t = q.getType()

      console.log(options.question)
      q.name = 'Enter question text here...'
      q.tag = guid()
      questionCounter++
       console.log(options.question.placeHolder)
    })

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* editor version:

**Comment by tsv2013** [comment]
SurveyJS Creator doesn't allow to create questions with the same names via UI. Each question in SurveyJS should have a unique name.If you modify it via code you are responsible for names consistency.

By the way, the name of a question is a unique identifier. In order to change question title, you need to change corresponding property - "q.title = 'Enter question text here...'"

**Comment by VishalWaman** [comment]
That helped, Thanks
