### ISSUE TITLE
Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'LocalStorageSurvey' exceeded the quota.

### ISSUE THREAD

**Issue by parmardhara** [surveyjs/survey-creator#645]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

I am not being able to upload image more than 2MB for image picker question in surveyjs creator

### What is the expected behavior?

Should allow atleast max size upto 2MB per image for image picker question in surveyjs creator

### How would you reproduce the current behavior (if this is a bug)?

upload image more than 2MB, it raises error as shown in the below screen:

![image](https://user-images.githubusercontent.com/51152178/71640923-65fef100-2cb9-11ea-9415-70fd6730d0d8.png)

### Specify your

* browser: Google Crome
* surveyjs creator version: 1.1.24

**Comment by tsv2013** [comment]
If your suestion related to the https://surveyjs.io/create-survey/ web page, this can happens if you are designing survey in anonymous mode, not logged in and your surveys JSON is stored in the local storage of your browser. This is the only way to save at least tempotary your work. But the local storage is limited and we can't overcome this limitation.

You need to develop surveys in our service (in this case images are stored in our service) or host SurveyJS Creator on your backend and control this behavior.
