### ISSUE TITLE
Unintuitive behavior for onOpenFileChooser

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#900]
### Are you requesting a feature, reporting a bug or ask a question?
Bug / Feature

### What is the current behavior?
The recently added `onOpenFileChooser` event fires when the creator would normally show the system file picker dialog. This allows us to create our own image picker.
The event is passed a callback for returning the picked file(s).
These files are then passed to the `onUploadFile` callback.

### What is the expected behavior?
When creating a custom file picker the files are already on a server and there is no need to upload them again.
Furthermore, in most cases there is no `File` object, just a string that contains a URL that points to the file.

Ideally `onUploadFile` should not be triggered when using the callback, instead the raw URI should just be used.

Currently I circumvent this by adding a listener for `onUploadFile`, that checks if a file is a `File` or a `string` and decides what to do based upon that. The issue with this workaround is that the callback for `onOpenFileChooser` does not accept a list of strings in its TypeScript definition and the only reason that it works in JS is because the types are not enforced, which does not seem like something I should depend on as a library user.

### How would you reproduce the current behavior (if this is a bug)?
```
editor.onOpenFileChooser.add((creator, options) => {
    // Skip picker return image url
    options.callback(['https://somedomain.com/someimage.png']);
}));
```

### Specify your

* browser: chrome latest
* editor version: latest

**Comment by tsv2013** [comment]
In original thread you told that event to show custom file chooser will be enough (https://github.com/surveyjs/survey-creator/issues/391#issuecomment-653481412)

If the thing is in typings only, you can cast arguments to <any> in TS as a workaround.

**Comment by SamMousa** [comment]
Yeah, it was a miscommunication.
I assumed the callback passed to the file chooser would be the same as the one to `onUploadFile` (ie it would skip that one).
Apologies for that!

Also, I can work around it since I don't use TS, so I don't have that typing issue. The issue with the workaround is that it depends on your internal implementation, which you are free to change at any point.

Since this API is relatively new, I thought it better to notice this behavior now while there is still a chance to change it (or choose not to) than notice it later when a lot of third parties could already be depending on it.

When implementing a custom file chooser we already get passed the creator instance.
If the custom file chooser wants to upload file using the default mechanism it can simply call `creator.uploadFiles()`.

Then after it is done uploading using *any* method it will call the callback with the file names of uploaded files. 

Alternatively, in case you do not want to break the current API I propose simply extending it: offer both callbacks.
So it could look something like this: 

```js
creator.onOpenFileChooser.add((creator, options) => {
    // Show file picker
    let pickedFile = pickSomething();
    if (pickedFile is already uploaded) {
        options.urlCallback([pickedFile]);
    } // pickedFile needs to be uploaded
        options.callback([pickedFile]);
    }
});
```

Note this is just pseudo code and I do not care about the names of the callback.

**Comment by tsv2013** [comment]
@SamMousa Sorry for delayed response, i'll try to free some time for this issue next week. Ping me here if it's urgent for you.

**Comment by SamMousa** [comment]
I'm in no rush at all, I have a workaround that's operational.
I prefer you take the time and come up with a great solution than rush it ;-)

**Comment by tsv2013** [comment]
Thank you @SamMousa !

**Comment by tsv2013** [comment]
I've finally returned back to this thread. I've re-read the thread and gone through our code.

What were the roots of the current design?
Single responsibility principle: One event (onOpenFileChooser) allows to override file chooser dialog and just return files chosen by user (as array of FIle object). Another event (onUploadFile) is responsible for the file uploading only and no more. And here use can filter selected files (e.g. limit by file size of picture size or more complex criteria).

Our internal code also uses this couple of events - getting files first and uploading them a bit later.
User can use one of these events or both of them. I think this flexible solution allows to support more scenarios. That's why we'd like to keep this behavior as is.

In your case as far as I understand, your custom file chooser at once overrides file selecting and file uploading. How many our users, do you think will use the same component? If the thing is in typings, then I can set argument type not `File[]` but `any[]` or even overload method as generic (I'm not sure but still can try) and you can use it without any type conversions.

What do you think? Or you have another idea how it can be implemented?

**Comment by SamMousa** [comment]
I'm unavailable for the week, I'll reply in detail after that, hope that's ok

**Comment by tsv2013** [comment]
It's absolutely ok
